emailtracking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tracking/', include('tracking.urls'))
]

tracking/urls.py
from django.urls import path, include
from django.http import HttpResponse
from . import views

app_name = 'tracking'
urlpatterns = [
    path("create-tracker/", views.create_tracker_form, name='create_tracker'),
    path("tracker-image-download/<uuid:id>/", views.get_identifier_image, name="url_of_emailed_tracker_image"),
    path("",lambda request: HttpResponse("Hello, Stranger.")),
    path("tracker-created-successfully/<uuid:pk>", views.trackerCreatedSuccessfully.as_view(), name="tracker_created_successfully"),

    #path('', views.IndexView.as_view(), name='index'),
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    #path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    #path('<int:question_id>/vote/', views.vote, name='vote'),
]

tracking/models.py
from django.db import models
import datetime
import uuid
from django.utils import timezone


# Create your models here.
class Tracker(models.Model):
	id = models.UUIDField(
         primary_key = True,
         default = uuid.uuid4,
         editable = False)
	recipient_email = models.EmailField()
	time_created = models.DateTimeField(default=timezone.now)
	recipient_name = models.CharField(max_length=100)
	email_subject = models.CharField(max_length=300)
	email_content = models.TextField()
	def __str__(self):
		return f"Tracker sent to {self.recipient_email} at {self.time_created}"
class TrackerHit(models.Model):
	tracker_id = models.ForeignKey(Tracker, on_delete=models.CASCADE)
	hit_date = models.DateTimeField(default=timezone.now)
	ip = models.CharField(max_length=100)

tracking/forms.py
from django import forms
from .models import Tracker
class TrackerCreationForm(forms.ModelForm):
	class Meta:
		model = Tracker
		fields = ["recipient_name","recipient_email","email_subject","email_content"]

tracking/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from PIL import Image, ImageDraw
from .forms import TrackerCreationForm
from django.urls import reverse
from .models import Tracker, TrackerHit
from django.template.loader import render_to_string
from django.conf import settings
img = Image.new('RGBA', (1, 1), color = (0,0,0,0))
from django.core.mail import send_mail,BadHeaderError



def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip
def renderEmailHtml(tracker):
	return "empty for now."
def publicImgUrl(tracker):
	relUrl = reverse("tracking:url_of_emailed_tracker_image",args=(tracker.id,))
	return "http://"+settings.SITE_IP+relUrl

def sendMail(tracker):
	subject = tracker.email_subject
	subject = subject.replace("\n","") #just in case
	recipient = tracker.recipient_email
	sender = settings.EMAIL_HOST_USER
	plain_content = tracker.email_content
	imgUrl = publicImgUrl(tracker)
	html_content = render_to_string("tracking/tracker_email_content.html",{"imgUrl":imgUrl,"email_content":plain_content})
	print(html_content)
	try:
		send_mail(subject,plain_content,sender,[recipient],html_message=html_content)
	except BadHeaderError:
		return False
	return True

def trackerCreationSuccessful(request,id):
	tracker = Tracker.objects.get(id=id)
	email_html = renderEmailHtml(tracker)
	return render(request,"tracking/tracker_created_successfully.html",{tracker:tracker,email_html:email_html})
class trackerCreatedSuccessfully(generic.DetailView):
	model = Tracker
	template_name = "tracking/tracker_created_successfully.html"
	def get_context_data(self,**kwargs):
		context = super().get_context_data(**kwargs)
		context["email_html"] = renderEmailHtml(context["tracker"])
		return context

def create_tracker_form(request):
	if request.method =='POST':
		form = TrackerCreationForm(request.POST)
		if form.is_valid():
			new_tracker = form.save(commit=False)
			new_tracker.save()
			#Add concurrency later, maybe.
			sendMail(new_tracker)
			return HttpResponseRedirect(reverse('tracking:tracker_created_successfully', args=(new_tracker.id,)))
	else:
		form = TrackerCreationForm()
	return render(request, 'tracking/create_tracker_form.html', {"form":form})
	

def get_identifier_image(request,id):
	#log visit
	ip = get_client_ip(request)
	hit = TrackerHit(ip=ip,tracker_id=Tracker.objects.get(id=id))
	hit.save()
	#make response
	response = HttpResponse(content_type='image/png')
	img.save(response, "PNG")
	return response

tracking/templates/tracking/create_tracker_form.html
<head>
	<title>Create A Tracker</title>
</head>
<body>
	<h1>Create a tracking email</h1>
	<form action="{% url 'tracking:create_tracker' %}" method="post"> {% csrf_token %}
		<fieldset>
			<label for="recipient_name">Recipient Name:</label><br>
			<input type="text" name="recipient_name" value="Unknown"><br>

			<label for="recipient_email">Recipient Email:</label><br>
			<input type="email" name="recipient_email" required><br>

			<label for="email_subject">Subject:</label><br>
			<input type="text" name="email_subject" value="A Matter of importance" required><br>

			<label for="email_content">Email Body:</label><br>
			<textarea name="email_content" required>Greetings. I delight in informing you that you've been tracked. Get rekt. Sincerely, bad news.</textarea><br>
			<input type="submit"><br>
		</fieldset>
	</form>
	{% if error_message %}<p><strong>Invalid Input{{ error_message }}</strong></p>{% endif %}



</body>

tracking/templates/tracking/tracker_created_successfully.html
<body>
	<h1>Tracker {{tracker}}</h1>
	<h2>Subject: {{tracker.email_subject}}</h2>
	<h3>Email Content Text:</h3>
	<p>{{tracker.email_content}}</p>
	<h3>Email Content Html:</h3>
	<p>{{email_html}}</p>
</body>

tracking/templates/tracking/tracker_email_content.html
<p>{{email_content}}</p>
<img src="{{imgUrl}}" alt="a cool image">
<p>Img url: {{imgUrl}}</p>